"""Score a full-lattice CLARA tuning function.

You write one function::

    def my_tuner(beam, target):
        '''beam: cheetah.ParticleBeam at the lattice entrance.
           target: np.array([mu_x, mu_y, sigma_x, sigma_y]) in metres, wanted at the
                   readout screen.
           returns: a configured cheetah.Segment.'''
        lattice = score.load_lattice()
        ...                                  # set magnets however you like
        return lattice

and hand it over::

    import score
    report = score.score(my_tuner)
    print(report)

`score()` runs your function against 100 random starting beams and 100 random targets,
tracks each beam through the lattice you hand back, measures the beam at
`CLA-FEH-DIA-SCR-01` (the FEBE hutch screen, s = 67.93 m) and reports how close you got.

Three things worth knowing before you start.

**Targets are reachable by construction.** Each one is generated by perturbing a
reference tune, tracking that beam, and reading off the moments it actually produced.
So for every case there is at least one magnet configuration that hits the target
exactly. Targets that lose the beam or land off the screen are rejected and redrawn.

**Evaluations are counted, not capped.** Every `track()` call on a lattice you got from
`load_lattice()` is counted and reported. Nothing stops you brute-forcing, but a method
that needs 10,000 simulator calls per beam would need 10,000 machine shots, so report
the number honestly — it is the figure that costs beam time.

**Only magnets may change.** The segment you return is checked against the reference:
same elements in the same order, and only quadrupole `k1`, corrector angles and
sextupole `k2` may differ. Anything else (drift lengths, cavity voltages, screen
positions) is a failed case.

**Baselines to beat.** Measured on 100 cases (20 for BO, which is slow):

    reference_tuner       173 um mean    0 evaluations   ignores the target entirely
    random_search_tuner    91 um mean   40 evaluations

Worth knowing before you reach for Bayesian optimisation: plain `gp_minimize` over the
~52 knobs upstream of the readout, on the same 40-evaluation budget, scores 93 um — no
better than random search. With fewer observations than dimensions the GP posterior
carries almost no information. BO wins comfortably on the 8-knob S04 problem in section
4 of the notebook; getting it to work at this scale means cutting the dimensionality,
warm-starting, or a trust region.

Budget roughly 0.1 s per simulator call: `random_search_tuner` takes ~8 minutes over
100 cases. Use `n_cases` to cut that down while iterating, but report the 100-case
number.

Run `python score.py` to score the built-in baselines on 20 cases.
"""

from __future__ import annotations

import inspect
import json
import time
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path

import cheetah
import numpy as np
import torch

HERE = Path(__file__).parent
LATTICE_JSON = HERE / "data" / "clara" / "lattice_data" / "CLARA_cheetah.json"
REFERENCE_TUNE_JSON = HERE / "reference_tune.json"

# The lattice starts after the S01 aperture, matching the kickoff notebook.
LATTICE_START = "cla_s01_sim_aper_01"

# FEBE hutch, s = 67.93 m, 11.6 um pixels, +/- 11.2 x 6.98 mm.
#
# Be aware when reading scores: the FEA arc leaves D_x = -3.85 m of residual dispersion
# here, so with the beams this benchmark uses (1e-4 energy spread) roughly 97% of the
# horizontal spot size is dispersion. Quadrupoles move sigma_x very little, and a tuner
# that ignores horizontal focusing entirely still scores well on that component. The
# vertical plane and both centroids are properly controllable. Point this at
# `cla_s07_dia_scr_04` (s = 47.6 m, upstream of the arc) for a readout where all four
# components respond to the magnets.
READOUT_SCREEN = "cla_feh_dia_scr_01"

# What a tuner is allowed to change, per element type.
TUNABLE = {
    cheetah.Quadrupole: ("k1",),
    cheetah.CombinedCorrector: ("horizontal_angle", "vertical_angle"),
    cheetah.Sextupole: ("k2",),
}

TARGET_LABELS = ("mu_x", "mu_y", "sigma_x", "sigma_y")

# A case counts as a hit when its mean absolute error is within this fraction of the
# target spot size — scale-free, so a tight target is not easier than a loose one.
# Reported at several tolerances: one number is either 0% or 100% for most methods.
HIT_TOLERANCES = (0.50, 0.25, 0.10)

_PENALTY_UM = 1e4  # error booked against a case that fails, loses the beam, or errors


# --------------------------------------------------------------------------------- #
# lattice
# --------------------------------------------------------------------------------- #


def elements_named(segment, name):
    """All elements with this name, as a list.

    `getattr` on a Segment returns a bare element for a unique name but a *list* if the
    name appears more than once, so code that assumes one or the other breaks silently.
    The CLARA lattice used to hit this: a copy of the F6B block (`cla_feh_mag_quad_04`,
    `cla_feh_mag_hvcor_03/04`, `cla_feh_dia_bpm_02`) was duplicated between SCR-03 and
    FEC2, where the machine has only a vacuum valve. That is fixed in the lattice file
    now, but going through here keeps the harness correct if it ever comes back.
    """
    found = getattr(segment, name)
    return found if isinstance(found, list) else [found]


@lru_cache(maxsize=1)
def _lattice_template() -> cheetah.Segment:
    """Parsed once; `load_lattice` clones it. Parsing the JSON costs ~5 s."""
    segment = cheetah.Segment.from_lattice_json(str(LATTICE_JSON)).partition_at(
        LATTICE_START, mode="after"
    )[-1]
    apply_tune(segment, reference_tune())
    return segment


def load_lattice(count_evaluations: bool = True) -> cheetah.Segment:
    """A fresh copy of the CLARA lattice from the S01 aperture onwards.

    Comes set to the reference tune. `track()` calls on the returned segment are
    counted (see `evaluations_of`).
    """
    segment = _lattice_template().clone()
    if count_evaluations:
        _instrument(segment)
    return segment


@lru_cache(maxsize=1)
def reference_tune() -> dict:
    """Magnet settings captured from the real machine (see reference_tune.json)."""
    return json.loads(REFERENCE_TUNE_JSON.read_text())["elements"]


def apply_tune(segment, tune: dict) -> None:
    """Write a {element_name: {property: value}} mapping into a segment."""
    for name, properties in tune.items():
        try:
            elements = elements_named(segment, name)
        except AttributeError:
            continue  # element is downstream of a partition — nothing to set
        for element in elements:
            for prop, value in properties.items():
                setattr(element, prop, torch.tensor(float(value), dtype=torch.float32))


def read_tune(segment) -> dict:
    """Pull the tunable settings back out of a segment."""
    tune = {}
    for element in segment.elements:
        for kind, properties in TUNABLE.items():
            if isinstance(element, kind):
                tune[element.name] = {p: float(getattr(element, p)) for p in properties}
    return tune


def _instrument(segment) -> None:
    """Count track() calls on a segment and everything inside it."""
    segment._evaluations = [0]
    original = segment.track

    def counted(incoming, *args, **kwargs):
        segment._evaluations[0] += 1
        return original(incoming, *args, **kwargs)

    segment.track = counted
    # Partitioning hands back new Segments that share elements; keep the same counter so
    # tuners that cut the lattice down still get counted.
    original_partition = segment.partition_at

    def partition(*args, **kwargs):
        parts = original_partition(*args, **kwargs)
        for part in parts:
            if isinstance(part, cheetah.Segment):
                part._evaluations = segment._evaluations
                part_original = part.track

                def counted_part(incoming, *a, _o=part_original, **kw):
                    segment._evaluations[0] += 1
                    return _o(incoming, *a, **kw)

                part.track = counted_part
        return parts

    segment.partition_at = partition


def evaluations_of(segment) -> int:
    """How many times this segment (or a partition of it) has been tracked."""
    return getattr(segment, "_evaluations", [0])[0]


# --------------------------------------------------------------------------------- #
# beams and targets
# --------------------------------------------------------------------------------- #


def sample_beam(rng, num_particles: int = 10_000) -> cheetah.ParticleBeam:
    """A starting beam at the lattice entrance, 4.2 MeV out of the gun.

    Randomised around the example beam in section 3 of the kickoff notebook. That beam
    has a very low emittance by CLARA standards; the Cheetah model has no L01 solenoids,
    so a realistic 1 um normalised emittance with 1e-3 energy spread grows to tens of
    millimetres by FEBE and misses the screen entirely. Keeping the notebook's beam
    family keeps the scoring task well posed. See the README note on sim2real.

    Particle coordinates come from torch's global RNG, so it is seeded from `rng` and
    restored afterwards. Without that the benchmark is not reproducible: different
    particles shift the measured moments, which changes how many draws `sample_target`
    rejects, which desynchronises `rng` for every later case.
    """

    def uniform(low, high):
        return torch.tensor(float(rng.uniform(low, high)))

    torch_state = torch.get_rng_state()
    torch.manual_seed(int(rng.integers(2**31)))
    try:
        return _beam_from(num_particles, uniform)
    finally:
        torch.set_rng_state(torch_state)


def _beam_from(num_particles, uniform) -> cheetah.ParticleBeam:
    return cheetah.ParticleBeam.from_parameters(
        num_particles=num_particles,
        energy=uniform(4.0e6, 4.4e6),
        mu_x=uniform(-5e-5, 5e-5),
        mu_px=uniform(-1e-5, 1e-5),
        mu_y=uniform(-5e-5, 5e-5),
        mu_py=uniform(-1e-5, 1e-5),
        sigma_x=uniform(0.7e-5, 1.4e-5),
        sigma_px=uniform(0.7e-6, 1.4e-6),
        sigma_y=uniform(0.7e-5, 1.4e-5),
        sigma_py=uniform(0.7e-6, 1.4e-6),
        sigma_tau=torch.tensor(1e-6),
        sigma_p=torch.tensor(1e-4),
        dtype=torch.float32,
    )


def measure(segment, beam) -> np.ndarray:
    """(mu_x, mu_y, sigma_x, sigma_y) in metres at the readout screen."""
    to_screen = segment.partition_at(READOUT_SCREEN, mode="after")[0]
    out = to_screen.track(beam)
    return np.array(
        [out.mu_x.item(), out.mu_y.item(), out.sigma_x.item(), out.sigma_y.item()]
    )


def _screen_half_extent(segment) -> tuple[float, float]:
    extent = elements_named(segment, READOUT_SCREEN)[0].extent
    return float(extent[1]), float(extent[3])


# How far the target generator wanders from the reference tune. Big enough that the
# targets are a real ask, small enough that the beam usually survives to the screen.
TARGET_K1_SPREAD = 0.20  # relative, per quadrupole
TARGET_KICK_SPREAD = 2e-6  # rad, per corrector plane
TARGET_CENTROID_LIMIT = 1.5e-3  # m — keep targets near the middle of the screen


def sample_target(rng, beam, segment, max_tries: int = 25) -> np.ndarray | None:
    """A target that is reachable for this beam, by construction.

    Perturbs the reference tune, tracks, and takes whatever moments come out. Draws that
    lose the beam or land far off centre are rejected.

    The `sigma_x` targets come out over a narrower range than `sigma_y`. That is
    physics, not a bug: the FEA arc leaves `D_x = -3.85 m` of dispersion at this screen,
    so with 1e-4 energy spread the horizontal spot is ~300 um of dispersion almost
    regardless of the quadrupoles. Horizontal focusing is only weakly controllable here
    — see the note on `READOUT_SCREEN`.
    """
    reference = reference_tune()
    half_x, half_y = _screen_half_extent(segment)
    limit_x = min(TARGET_CENTROID_LIMIT, 0.9 * half_x)
    limit_y = min(TARGET_CENTROID_LIMIT, 0.9 * half_y)
    quads = sorted({e.name for e in segment.elements if isinstance(e, cheetah.Quadrupole)})
    correctors = sorted(
        {e.name for e in segment.elements if isinstance(e, cheetah.CombinedCorrector)}
    )
    for _ in range(max_tries):
        apply_tune(segment, reference)
        for name in quads:
            for element in elements_named(segment, name):
                scaled = float(element.k1) * (1.0 + rng.normal(0.0, TARGET_K1_SPREAD))
                element.k1 = torch.tensor(scaled, dtype=torch.float32)
        for name in correctors:
            for element in elements_named(segment, name):
                element.horizontal_angle = torch.tensor(
                    float(rng.normal(0.0, TARGET_KICK_SPREAD)), dtype=torch.float32
                )
                element.vertical_angle = torch.tensor(
                    float(rng.normal(0.0, TARGET_KICK_SPREAD)), dtype=torch.float32
                )
        moments = measure(segment, beam)
        apply_tune(segment, reference)
        if not np.isfinite(moments).all():
            continue
        if abs(moments[0]) > limit_x or abs(moments[1]) > limit_y:
            continue
        if moments[2] <= 0 or moments[3] <= 0:
            continue
        return moments
    return None


@lru_cache(maxsize=4)
def make_cases(n_cases: int = 100, seed: int = 0, num_particles: int = 10_000):
    """The fixed benchmark: n_cases (beam, target) pairs. Same seed, same cases."""
    rng = np.random.default_rng(seed)
    scratch = load_lattice(count_evaluations=False)
    cases = []
    while len(cases) < n_cases:
        beam = sample_beam(rng, num_particles)
        target = sample_target(rng, beam, scratch)
        if target is not None:
            cases.append((beam, target))
    return tuple(cases)


# --------------------------------------------------------------------------------- #
# validation
# --------------------------------------------------------------------------------- #


def _structure(segment) -> list[str]:
    return [f"{type(e).__name__}:{e.name}" for e in segment.elements]


def _fixed_features(segment) -> dict:
    """Everything a tuner is *not* allowed to touch, as plain floats."""
    fixed = {}
    for index, element in enumerate(segment.elements):
        allowed = next(
            (props for kind, props in TUNABLE.items() if isinstance(element, kind)), ()
        )
        for feature in element.defining_features:
            if feature in allowed or feature == "name":
                continue
            value = getattr(element, feature, None)
            if isinstance(value, torch.Tensor):
                fixed[(index, feature)] = tuple(
                    np.round(value.detach().flatten().numpy().astype(float), 9)
                )
    return fixed


def check_segment(returned, reference, _structure_of=None, _features_of=None) -> str | None:
    """None if the returned segment is a legal retune, else why it is not.

    `_structure_of` / `_features_of` let the scorer pass the reference's precomputed
    structure and fixed features, which otherwise get rebuilt on every case.
    """
    if not isinstance(returned, cheetah.Segment):
        return f"expected a cheetah.Segment, got {type(returned).__name__}"
    expected_structure = _structure_of if _structure_of is not None else _structure(reference)
    if _structure(returned) != expected_structure:
        return "lattice structure changed (elements added, removed, renamed or reordered)"
    expected = _features_of if _features_of is not None else _fixed_features(reference)
    actual = _fixed_features(returned)
    changed = [
        f"element {i} {returned.elements[i].name}.{feature}"
        for (i, feature), value in expected.items()
        if actual.get((i, feature)) != value
    ]
    if changed:
        shown = ", ".join(changed[:3])
        more = f" (+{len(changed) - 3} more)" if len(changed) > 3 else ""
        return f"non-tunable properties changed: {shown}{more}"
    return None


# --------------------------------------------------------------------------------- #
# scoring
# --------------------------------------------------------------------------------- #


@dataclass
class CaseResult:
    index: int
    target: np.ndarray
    achieved: np.ndarray | None
    error_um: float
    relative_error: float
    evaluations: int
    seconds: float
    failure: str | None = None

    def hit(self, tolerance: float) -> bool:
        return self.failure is None and self.relative_error <= tolerance


@dataclass
class Report:
    name: str
    cases: list[CaseResult] = field(default_factory=list)

    @property
    def errors_um(self) -> np.ndarray:
        return np.array([c.error_um for c in self.cases])

    @property
    def relative_errors(self) -> np.ndarray:
        return np.array([c.relative_error for c in self.cases])

    @property
    def mean_error_um(self) -> float:
        return float(self.errors_um.mean())

    @property
    def median_error_um(self) -> float:
        return float(np.median(self.errors_um))

    @property
    def worst_error_um(self) -> float:
        return float(self.errors_um.max())

    def hit_rate(self, tolerance: float) -> float:
        return float(np.mean([c.hit(tolerance) for c in self.cases]))

    @property
    def failures(self) -> list[CaseResult]:
        return [c for c in self.cases if c.failure is not None]

    @property
    def evaluations_per_case(self) -> float:
        return float(np.mean([c.evaluations for c in self.cases]))

    @property
    def seconds(self) -> float:
        return float(sum(c.seconds for c in self.cases))

    def per_component_um(self) -> dict:
        rows = [
            np.abs(c.achieved - c.target) * 1e6
            for c in self.cases
            if c.achieved is not None
        ]
        if not rows:
            return {label: float("nan") for label in TARGET_LABELS}
        stacked = np.array(rows)
        return dict(zip(TARGET_LABELS, stacked.mean(axis=0)))

    def __str__(self) -> str:
        lines = [
            f"{self.name}  —  {len(self.cases)} cases at {READOUT_SCREEN}",
            f"  mean error       {self.mean_error_um:10.2f} um",
            f"  median error     {self.median_error_um:10.2f} um",
            f"  worst error      {self.worst_error_um:10.2f} um",
            "  hit rate (mean error within x% of the target spot size):",
            *(
                f"      within {t:.0%} {self.hit_rate(t):10.1%}"
                for t in HIT_TOLERANCES
            ),
            f"  evaluations      {self.evaluations_per_case:10.1f} per case",
            f"  failed cases     {len(self.failures):10d}",
            f"  wall clock       {self.seconds:10.1f} s",
            "  per component (mean |error|, um):",
        ]
        lines += [
            f"      {label:9s} {value:10.2f}"
            for label, value in self.per_component_um().items()
        ]
        if self.failures:
            lines.append("  failures:")
            seen = {}
            for case in self.failures:
                seen.setdefault(case.failure, []).append(case.index)
            for reason, indices in seen.items():
                shown = ", ".join(str(i) for i in indices[:5])
                more = f" (+{len(indices) - 5} more)" if len(indices) > 5 else ""
                lines.append(f"      [{shown}{more}] {reason}")
        return "\n".join(lines)


def score(
    tune,
    n_cases: int = 100,
    seed: int = 0,
    num_particles: int = 10_000,
    name: str | None = None,
    progress: bool = True,
) -> Report:
    """Score a tuning function against the benchmark.

    `tune` is called once per case as `tune(beam, target)`, or as
    `tune(beam, target, lattice)` if it takes a third argument — in which case it is
    handed a fresh, evaluation-counting lattice rather than having to call
    `load_lattice()` itself. It must return a configured `cheetah.Segment`.

    `target` is `np.array([mu_x, mu_y, sigma_x, sigma_y])` in **metres**.
    """
    name = name or getattr(tune, "__name__", "tuner")
    wants_lattice = len(inspect.signature(tune).parameters) >= 3
    reference = load_lattice(count_evaluations=False)
    reference_structure = _structure(reference)
    reference_features = _fixed_features(reference)
    report = Report(name=name)

    for index, (beam, target) in enumerate(
        make_cases(n_cases, seed, num_particles)
    ):
        lattice = load_lattice()
        started = time.time()
        failure, achieved = None, None
        try:
            returned = tune(beam, target, lattice) if wants_lattice else tune(beam, target)
        except Exception as exc:  # a tuner that crashes fails that case, not the run
            failure, returned = f"{type(exc).__name__}: {exc}", None
        # Count what the tuner spent before the scorer adds its own measurement.
        evaluations = evaluations_of(lattice) + (
            evaluations_of(returned)
            if isinstance(returned, cheetah.Segment) and returned is not lattice
            else 0
        )
        if failure is None:
            failure = check_segment(
                returned, reference, reference_structure, reference_features
            )
        if failure is None:
            achieved = measure(returned, beam)
            if not np.isfinite(achieved).all():
                failure, achieved = "beam lost (non-finite moments at the screen)", None

        if failure is None:
            error_um = float(np.abs(achieved - target).mean() * 1e6)
            relative = error_um / float(target[2:].mean() * 1e6)
        else:
            error_um, relative = _PENALTY_UM, _PENALTY_UM

        report.cases.append(
            CaseResult(
                index=index,
                target=target,
                achieved=achieved,
                error_um=error_um,
                relative_error=relative,
                evaluations=evaluations,
                seconds=time.time() - started,
                failure=failure,
            )
        )
        if progress:
            case = report.cases[-1]
            status = case.failure or f"{case.error_um:8.2f} um  ({case.relative_error:5.1%})"
            print(f"  [{index + 1:3d}/{n_cases}] {status}", flush=True)
    return report


# --------------------------------------------------------------------------------- #
# baselines
# --------------------------------------------------------------------------------- #


def reference_tuner(beam, target, lattice):
    """Do nothing: hand back the reference tune, ignoring the target.

    The floor any real method has to beat.
    """
    return lattice


def random_search_tuner(beam, target, lattice, n_calls: int = 40, seed: int = 0):
    """Scale the quadrupoles and kick the correctors at random; keep the best draw.

    Deliberately weak, and deliberately cheap to understand. Tunes the magnets in S07
    and the FEA arc only — the 20-odd knobs closest to the readout screen.
    """
    rng = np.random.default_rng(seed)
    names = sorted(
        {
            e.name
            for e in lattice.partition_at(READOUT_SCREEN, mode="after")[0].elements
            if isinstance(e, (cheetah.Quadrupole, cheetah.CombinedCorrector))
            and e.name.split("_")[1] in ("s07", "fea")
        }
    )
    baseline = {n: read_tune(lattice)[n] for n in names}
    best_error, best = np.inf, baseline
    for _ in range(n_calls):
        trial = {}
        for name, properties in baseline.items():
            trial[name] = {
                prop: (
                    value * (1.0 + rng.normal(0.0, 0.05))
                    if prop == "k1"
                    else float(rng.normal(0.0, 2e-5))
                )
                for prop, value in properties.items()
            }
        apply_tune(lattice, trial)
        moments = measure(lattice, beam)
        error = np.abs(moments - target).mean() if np.isfinite(moments).all() else np.inf
        if error < best_error:
            best_error, best = error, trial
    apply_tune(lattice, best)
    return lattice


BASELINES = (reference_tuner, random_search_tuner)


def main() -> None:
    n_cases = 20  # the headline benchmark is 100; 20 keeps the self-test quick
    print(f"Scoring built-in baselines on {n_cases} cases\n")
    for tuner in BASELINES:
        print(f"--- {tuner.__name__} ---")
        report = score(tuner, n_cases=n_cases, progress=False)
        print(report, "\n")


if __name__ == "__main__":
    main()
